logging:
# log into files 
#  file: 
#  path: 
  level:
    root: WARN
    org:
      springframework: TRACE
        
        

#To See H2 Console in Browser
#http://localhost:8080/h2-console
#Enable H2 console
spring:
  h2:
    console:
      enabled: true
  
##DB2  
  datasource: 
    url: jdbc:h2:mem:testdb;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  #JPA/HIBERNATE
  jpa:
    show-sql: true
    ##if want to use schema.sql , please set spring.jpa.hibernate.ddl-auto=none
#    hibernate:
#      ddl-auto: create-drop
#      dialect: org.hibernate.dialect.H2Dialect
  #ssl
server:
  port: 9090
#  ssl:
#    key-store: file:./mykey.jks
#    key-store-password: letmein
#    key-password: letmein
    
##customize properties
taco: 
  orders:
    pageSize: 1

          
---
spring: 
  profiles: prod
  
  datasource: 
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword
    
logging:
  level:
    tacos: WARN



