server:
  port: 8761

#Eureka 
eureka: 
  instance: 
    hostname: localhost
  client:
    #fetch-registry, resiter-with-eureka tell it how it should interact w
    fetch-registry: false
    register-with-eureka: false
    #service-url - contains a map of zone names to one or more URLS of Eureka servers in that zone
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    #enable-self-preservation:false is useful for the development
    enable-self-preservation: false 
    
---
spring: 
  profiles: eureka-1
  application: 
    name: eureka-1

server:
  port: 8761

eureka:
  instance:
    hostname: eureka1.tacocloud.com

other: 
  eureka:
    host: eureka2.tacocloud.com
    prot: 8761

---

spring:
  profiles: eureka-2
  application: 
    name: eureka-2

server:
  port: 8762
  
eureka:
  instance:
    hostname: eureka2.tacocloud.com
    
other: 
  eureka: 
    host: eureka1.tacocloud.com
    port: 8761
   
  