server:
  port: 8888
  
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yanfang93171/tacocloud-config
          #search-path: config,moreConfig
          #default-label: override default label or branch 
          #username:
          #password:
#        encrypt: #config server still serve encrpted 
#          enabled: false

          
          